[build]
  publish = "."
  command = ""

[context.production]
  environment = { NODE_VERSION = "16.x", NPM_VERSION = "8.x", ENABLE_FACE_DETECTION = "true" }

[context.deploy-preview]
  environment = { NODE_VERSION = "16.x", NPM_VERSION = "8.x", ENABLE_FACE_DETECTION = "true" }

[context.branch-deploy]
  environment = { NODE_VERSION = "16.x", NPM_VERSION = "8.x", ENABLE_FACE_DETECTION = "true" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS and security headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; img-src 'self' data: blob: https:; media-src 'self' data: blob: https:; connect-src 'self' blob: https:; worker-src 'self' blob:;"
    Access-Control-Allow-Origin = "*"
