services:
  - type: web
    name: mood-based-music-player
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mood_based_music_player:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 8000
